dungeon-revealer/dungeon-revealer

app.js

Hello,
First, greetings for your great job. This is exactly what i was looking for. It saves me few weekends of work :D
However i noticed that players could cheat : 
- If you type /dm on a client and press the back button, you can see the map flashing.
- If you type /dm/map on a client, you simply see the map.
This is a small fix for those cases. If a player goes there he just see : not found. DM of course can still see them.
Please have a review of the modifications and integrate them if you find them useful.
Best regards,
Cédric.

Prevents the DM screen to be viewed by non localhost clients

---

README.md
app.js
package.json

this pull request removes the localhost header check, which exposes the dm endpoints without protection by default. Setting the environment variable `DM_PASSWORD` protects the dm routes by prompting for a password. 
Closes #24

feat: allow setting a password for the dm area

---

README.md

was accidentally removed while rebasing in #48

chore: add travis build badge

---

.travis.yml

Added stages to the travis build. The travis build first installs dependencies and caches them, then it runs the linter and builds, then it builds and tests a docker image. If there is a tag, it builds the binaries, deploys a draft release on Github that a maintainer can review and publish, and pushes a docker image to dockerhub with the tags latest and whatever the git tag is. You can see it in action on my [fork](https://travis-ci.com/maxb2/dungeon-revealer/builds).
For the github deployment, you need to generate a [personal access token](https://github.com/settings/tokens) and save it as the environment variable `GITHUB_OAUTH_TOKEN` in the [travis-ci](https://travis-ci.org/apclary/dungeon-revealer/settings) settings. For the dockerhub deployment, you need to store your username and …

Update travis with automatic deployments

---

.dockerignore
.gitignore
.npmignore
app.js

Moved uploads to the app source directory. Added a .npmignore file to exclude uploads folder in builds. Fixes #46.

Fix uploads dir

---

.dockerignore
Dockerfile

I restructured things to try to reduce the docker image size. 
- Don't copy `build`,`data`,`.git`, or the binaries into the container.
- Run everything in one command to reduce the number of intermediate containers.
- Don't include the binaries built by `npm install`.

Reducing docker image size

---

Dockerfile

`node:10-alpine` is much smaller than `node:10`.

docker: change base image to node:10-alpine

---

.travis.yml

This changes how we deploy the binaries as suggested [here](https://github.com/apclary/dungeon-revealer/pull/104#issuecomment-507015258). Binaries are packaged in their own zip based on system, e.g. `dungeon-revealer-linux-v1.2.0.zip`. I also included a copy of the readme in each zip.

Travis split archives

---

src/dm-area/dm-map.js
src/feather-icons.js
src/player-area.js
src/style.css
src/toolbar.js
src/util.js

adjusts the visual appearance of the player toolbar according to the dm toolbars.
Additionally, when doing a long press on either the `Zoom In` or `Zoom Out` button, the map is zoomed in/out continuously until the user releases the long press.

feat: redesign player toolbar

---

public/index.html
src/hooks/use-long-press.js
src/index.js
src/pan-zoom.js
src/player-area.js

The app was a mess on an iPad. Safari is horrible, I had to reimplement how to pinch-zoom works on touch devices... Ended up writing a new PanZoom view. I also reduced the maximum map size, as iPhones and iPads were constantly crashing due to out-of-memory issues. I also removed the zoom animations (when holding the zoom in and zoom out buttons), because it also caused some buggy behavior, I do not think that their absence is that bad.
Also updates react-spring to a 9.0.0 canary version which has a nice feature (SpringValue, basically a two-way data binding for style attributes) that really helped me with keeping the style updates performant.
I tested it on an iPad with iOS 13, Google Chrome (Desktop), Google Chrome (Tablet Mode) and Safari Desktop. Everything seemed to work fine. If …

fix: player-area ios safari compat

---

src/dm-area/dm-map.js

fix: shroud tool should cover complete tiles when snapping the selection to the grid

---

.travis.yml
CONTRIBUTING.md
Dockerfile
Dockerfile-armbuild
package.json

This adds the ability for travis-ci to build an executable for the armv7 architecture, most popularly used in the Raspberry Pi. See issue #256. The travis servers run on x86/64 machines incapable of producing arm binaries. You have to emulate an arm machine to build the binary in.
This pull request does three things:
- In package.json, separate the binary compilation commands from the build script allowing a choice between architectures.
- Setup the travis build environment to emulate arm using qemu. Mostly adapted from [here](https://developer.ibm.com/linuxonpower/2017/07/28/travis-multi-architecture-ci-workflow/).
- Compile the arm executable in an [arm docker container](https://hub.docker.com/r/arm32v7/node).
The new scripts for compilation of binaries are needed because the build will …

Travis: Add build for ARMv7 architecture

---

src/dm-area/index.js
src/player-area.js
src/splash-screen.js

Currently, the players only see a black screen when no map is shared.

fix(player-area): show splash screen when no map is shared with the players

---

bin/dungeon-revealer

... via the HOST environment variable.
Closes #289

feat: allow configuring the host on which dungeon-revealer will listen for http requests

---

.travis.yml

Adds a check for binary compilation in the initial build stage on Travis. Adresses [this](https://github.com/dungeon-revealer/dungeon-revealer/pull/254#issuecomment-605513930).

Travis: add compilation check 

---

.github/workflows/build-binaries.yml
.github/workflows/build-ci.yml
.travis.yml

This PR partially migrates our CI/CD from Travis to Github Actions.
Fixes #182, allows #254 to be merged.
Actions Features:
- **Checks.** Branch and Pull Request checks are performed for node.js versions `10.x` and `12.x`. 
- **Compilation.** x64 binaries are compiled in their native operating systems instead of using cross compilation on Linux. Compiling natively in Windows fixes #182. 
- **Deployment.** On a tagged branch, a draft release is created and has the packages automatically uploaded to it.
Travis is still used for branch checks and Dockerhub deployment. See #363 for the full migration to Actions.

Github Actions for CI and Binary Deployment

---

.github/workflows/build-docker.yml

This imports a build cache from the [docker registry](https://hub.docker.com/repository/registry-1.docker.io/maxb2/dungeon-revealer/tags?page=1) when building images for release. After the build, it tries to export a build cache for each platform to the registry. 
[Test tag](https://github.com/maxb2/dungeon-revealer/runs/661837365)
The build will try to cache from the registry first. If that fails, it will build from the local build cache and takeover at the step that the previous build failed. If that fails, the image will be built from scratch with no cache. This way a valid build will always be built.
I separated the cache export to its own step because the connection to the registry [fails intermittently](https://github.com/docker/buildx/issues/271). I also allowed the cache export to …

Use registry cache for docker

---

.github/workflows/build-binaries.yml

This changes the docker image for arm compilation to Node 10. The maximum memory allocation has to be increased as well. 
Fixes #551. We should tag and release this as v1.8.1

fix: arm docker node 10

---

README.md

This replaces the old Discord link with one that never expires.

fix: replace expired discord link

---

.dockerignore
.github/workflows/deploy-wiki.yml
wiki/Community-Showcase.md
wiki/Contributing.md
wiki/Dice-Macros.md
wiki/Getting-Started.md
wiki/Grid.md
wiki/Home.md
wiki/Hosting.md
wiki/Install.md
wiki/Notes.md
wiki/Tokens.md
wiki/_Sidebar.md

This adds the contents of the wiki to the repository and adds an action to deploy any changes to the `wiki/` directory.
~~Blocked by #594.~~
@n1ru4l, can you set a new secret `GH_PAT` with the token generated from [here](https://github.com/settings/tokens/new?scopes=repo&description=wiki%20page%20creator%20token)? It's for [Decathlon/wiki-page-creator-action](https://github.com/marketplace/actions/wiki-page-creator-action)

Actions wiki deploy

---

.github/workflows/build-binaries.yml

This builds binaries on commits to master and uploads all binary zip files to the artifact `dungeon-revealer-binaries-${{ github.sha }}`.
Example [artifact](https://github.com/maxb2/dungeon-revealer/suites/942888993/artifacts/11682651) for master build.

Actions: build binaries on master

---

.github/workflows/build-binaries.yml
.github/workflows/discord-master-updates.yml
.github/workflows/discord-releases.yml

This creates a draft prerelease page for binary builds on master. A discord message is sent whenever a release is published.
**TODO**

Actions: master branch prerelease and discord notification

---

package.json

The issue and git repository links in package.json are pointing at the old repo.

fix: package.json git links

---

.github/workflows/build-binaries.yml
.github/workflows/discord-master-updates.yml
.github/workflows/discord-releases.yml

This changes the automated discord messages to [embeds](https://birdie0.github.io/discord-webhooks-guide/structure/embeds.html). Closes #666 :smiling_imp: 
The title links to a page that compares the previous master branch to the new one. The message body lists all the new commits with links.
The title and the body link to the release page. The body of the release is quoted (I'm considering changing this to a code block). I haven't been able to get #feedback to link to the text channel in discord. It might not be possible yet.
The title links to the build workflow where you can download the build artifacts. The description lists the included commits with links.

Actions: discord embed messages

---

wiki/Community-Showcase.md

Add a podcast that discusses dungeon-revealer to the Community Showcase. 
@nonplayer, let me know if this is okay and if I should add or change anything.

wiki: add BDaB podcast episode to Community Showcase

---

README.md

This sets the Heroku Deploy button to target the v1.10.3 tag. Previously, it would deploy the master branch which can sometimes be broken, see #794. We would also have to update the link manually every time we make a new release.

docs: set heroku button to target tag v1.10.3

---

.github/workflows/build-binaries.yml
.github/workflows/build-docker.yml
.github/workflows/deploy-wiki.yml
.github/workflows/discord-master-updates.yml
.github/workflows/discord-releases.yml
scripts/set-git-tag-env.js

The `set-env` command has been [deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) in Actions. This updates the actions workflows to use the new [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).

fix: actions environment

---

.github/workflows/build-docker.yml

From a Build Docker run:
```
Unexpected input(s) 'buildx-version', 'qemu-version', valid inputs are ['version', 'driver', 'driver-opts', 'buildkitd-flags', 'install', 'use', 'endpoint']
```

actions: remove extraneous options from docker/setup-buildx-action

---

.github/workflows/build-binaries.yml
scripts/set-git-tag-env.js

The `set-git-tag-env.js` script didn't work with the new environment in Actions (#886). This replaces that script with a bash pattern substitution.

fix(actions): set GH_TAG env

---

.github/workflows/build-binaries.yml
.github/workflows/build-ci.yml
.github/workflows/build-docker.yml
.github/workflows/deploy-wiki.yml
.github/workflows/discord-master-updates.yml
.github/workflows/discord-releases.yml

This addresses all of the recent warnings in the Actions runs:
- Pin runner os to `ubuntu-20.04`
- Remove deprecated `repository` option from `docker/build-push-action@v2`
[Test runs](https://github.com/maxb2/dungeon-revealer/runs/1466409398) on my fork.

Actions remove warnings

---

wiki/Getting-Started.md
wiki/Tokens.md

See the commits as they're very self explanatory.
The wiki has some hard coded links that took you out of the main wiki and pointed to a forked version.
I did a search and replace on all /maxb2/dungeon-revealer with dungeon-revealer/dungeon-revealer

Updated wiki pages to fix some links and correct some details

---

src/dm-area/components/html-container.tsx

Saw the issue about the link text in the notes not looking like links. There were two ways to fix it, but I chose to just edit the css.

added link styling in notes

---

.github/workflows/build-binaries.yml

This simplifies the creation of the Github Release and uploading of the assets using [softprops/action-gh-release](https://github.com/softprops/action-gh-release). The previous action, [actions/upload-release-asset](https://github.com/actions/upload-release-asset), has been deprecated.

Actions release

---

Dockerfile

Alpine3.13 uses a 64-bit library in musl. This can't be run on 32-bit hardware (raspi).
Fixes #1394

Docker alpine downgrade

---

Dockerfile

This changes the docker base image to node:16-slim which is based on Debian Buster. The final image size does increase by about 40%.
Related #1397, #1394

Docker use node:16-slim

---

.dockerignore
.github/workflows/build-ci.yml
.gitignore
package.json
scripts/prebuild.js
server/env.ts
server/index.js

This displays a message about the version at runtime based on information gathered at build time from `package.json` and [`git describe --tags`](https://git-scm.com/docs/git-describe#_description). A prebuild script at `scripts/prebuild.js` gathers all the information and writes it to `server/version.ts` with the following structure:
```typescript
export const appversion = '1.16.0';  // Version from package.json.
export const status = 'development';  // status = 'release' || 'development' || 'unknown'
export const tag = 'v1.16.0';  // Version from `git describe --tags`.
export const commit = '60c7b82';  // HEAD commit.
export const commits_ahead = '84';  // How many commits ahead of tag we are.
export const obj = 'g60c7b82';  // Commit-ish object from `git describe --tags`. Currently …
```

feat: add version to log output

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This adds definition files for [VS Code's dev container](https://code.visualstudio.com/docs/remote/create-dev-container). It allows you to develop in a docker container while still using the VS Code app. It's my preferred way to develop now and is completely optional to use for whoever clones this down.

feat: add vscode devcontainer

---

package-lock.json
package.json

`busboy` recently had a major version update which breaks `connect-busboy@0.0.2`.
This pins `connect-busboy@0.0.3` to which in turn pins `busboy@0.3.1`.
See https://github.com/mscdex/connect-busboy/issues/21

fix: pin connect-busboy@0.0.3

---

.github/workflows/build-binaries.yml
.github/workflows/build-ci.yml
.github/workflows/build-docker.yml
.github/workflows/deploy-wiki.yml
.github/workflows/discord-master-updates.yml
.github/workflows/discord-releases.yml

This addresses the [Node 12 deprecation warnings for github actions](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). It also simplifies the docker image deployment as the previous caching strategy was no longer working.

Fix: actions dep versions and simplify docker deploy

---

.github/workflows/build-docker.yml
README.md
wiki/Install.md

Feat: use Github Container Registry instead of Docker Hub

---

.github/workflows/deploy-wiki.yml
wiki/_Sidebar.md

This makes it so forks aren't trying to deploy to the `dungeon-revealer/dungeon-revealer` wiki but the `fork-owner/dungeon-revealer` wiki.

Fix: deploy wiki to repo owner namespace
