dungeon-revealer/dungeon-revealer

app.js
package.json
public/javascripts/map.js
public/javascripts/settings.js
views/dm.jade

Enhancements 
- added a square cursor option
- added a cursor outline
Major Changes 
- Added a new cursor layer where the cursor outline is drawn and the click and mouse move events are handled. 
- Abstracted mask definition, used for both outline and drawing, into separate function
Thoughts 
- Major complexity came from drawing smooth paths between rectangles. Waded into a real swamp.  
Let me know if you want me to change anything.

Add square cursor and cursor outline

---

public/javascripts/common.js
public/javascripts/dm-app.js
public/javascripts/map.js
public/javascripts/player-listener.js
public/javascripts/settings.js
views/player.jade

I have added a query library to add zooming on players screen.
I also have added the rendering to only the times when the image is sent using the button. (Helps a lot on larger images and screens)
I am also working on refactoring and cleaning up the overall project. This were some quick fix's I needed for my game.

Added zooming + Better performance for large images.

---

public/javascripts/map.js
public/stylesheets/style.css
views/dm.jade
views/layout.jade

This pull request adds touch event handlers for the admin interface, which allows revealing maps on tablets like the iPad.

feat: support drawing on tablets

---

public/javascripts/map.js

This pull request changes the drawing behavior from drawing everything towards only drawing the latest two points. This results in way better performance when drawing (revealing) big chunks of a map.

perf: improve the performance of drawing continuously

---

.dockerignore
Dockerfile
README.md

I've added a Dockerfile to create an image out of this app using the instructions from [here](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/). 
It is also possible to set up a Docker Hub repo to [follow a github repository](https://docs.docker.com/docker-hub/builds/link-source/). 
I updated the README to include instructions to run the docker container. Feel free to set up your own hub repo and point to it instead of mine.

Add Docker 

---

.travis.yml
README.md
package-lock.json
package.json

Probably needs a docker build step added, but this performs linting.

Added travis-ci

---

Dockerfile

Fixes apclary/dungeon-revealer#50.

Changed Dockerfile to work with react framework

---

src/dm-area/dm-map.js

This pull request adds a new tool `Select Area`. The DM can now switch between the `Select Area` and the `Brush` tool.
The new tool allows the dm to select a square area that he wants to reveal or shroud.
Closes #36
I created a preview gif

feat: add area select tool

---

CONTRIBUTING.md
README.md

Updated the readme and added contributing. Resolves #49.
- Removed obsolete node installation instructions
- Added instructions for running the executables
- Updated the usage section reflecting the new features
- Moved the contributing section to CONTRIBUTING.md

Update readme to reflect new features

---

.travis.yml

This adds a docker deployment with the `dev` tag for commits on the master branch. We can turn off all builds on dockerhub if we use this.
Resolves #59.

travis: add docker dev deployment

---

package.json
src/dm-area/dm-map.js
src/dm-area/index.js
src/dm-area/modal.js
src/dm-area/select-map-modal.js
src/dm-area/toolbar.js
src/object-layer.js
src/player-area.js
src/style.css
src/util.js

feat: admin ui revamp

---

.travis.yml

This deploys the binaries in a zip file so that they keep the executable bit.
Fixes #92.

Travis zip binary deployment

---

src/dm-area/index.js

Bug Reproduction (on dm section):
1. Select any map in modal
2. Open incognito tab
3. Delete the selected map in an incognito window
4. Reload initial window
5. You see a blank page
This adds a check on whether the loaded map/live map id is actually available

fix: handle edge case where map got deleted

---

src/dm-area/dm-map.js

This fixes a regression where the coordinates used for revealing are incorrect on touch screen devices.

fix(dm-area): use correct reveal coordinates

---

bin/dungeon-revealer
package.json

Log dm section and player section URLs.

feat: better server output

---

src/dm-area/select-map-modal.js

limit map title to one line and use an ellipsis

fix: title multiline wrap in select map modal

---

src/dm-area/dm-map.js
src/dm-area/index.js
src/dm-area/select-map-modal.js

fix: show map library in case live map or loaded map is not available

---

README.md
src/dm-area/dm-map.js
src/dm-area/index.js
src/hooks/use-is-key-pressed.js
src/hooks/use-on-key-down.js
src/input.js
src/object-layer/dm-token-renderer.js

Adds the following key events:
while alt key is pressed: treat everything like move mode
1: move tool
2: area tool
3. brush tool
4: mark tool
5: token tool
shift: toggle reveal/hide mode
CMD/Ctrl + S: push map to players

feat: add key events to the editor.

---

README.md
app.js

The password functions have been split from authMiddleware to authMiddlewareDM & authMiddlewarePC. A challenge screen will only show if the corresponding environment variable has been set from command line.
process.env.PC_PASSWORD
process.env.DM_PASSWORD
_____
Closes #208

Authorization Fix for DM & PCs (Bug #208)

---

package.json
src/object-layer/area-marker-renderer.js
src/object-layer/area-marker.js
yarn.lock

Since we now have tokens, it makes more sense to shorten the duration of a "point of interest". This also changes the implementation and removes quite some code.

feat: change point of interest animation

---

src/object-layer/dm-token-marker.js
src/object-layer/dm-token-renderer.js

fix: limit token context menu to viewport

---

README.md
app.json

Created app.json and modified readme.md to include instructions on deploying to Heroku for web-based access.

feat: Heroku deployment with app.json

---

src/hooks/use-is-key-pressed.js

fix(useIsKeyPressed): reset value when blurring the window.

---

src/dm-area/dm-map.js
src/object-layer/token-marker.js

fix: cursor position mismatch

---

server/index.js
src/dm-area/index.js
src/player-area.js

feat: require websocket authentication

---

bin/dungeon-revealer
server/env.js
server/index.js

Should resolve the confusions mentioned in https://github.com/dungeon-revealer/dungeon-revealer/pull/299#issuecomment-606014596 by @jonhoo

fix: better start output

---

src/dm-area/select-map-modal.js
src/dm-area/select-token-marker-reference-modal.tsx

fix: layout issues

---

package.json

Fixes https://github.com/dungeon-revealer/dungeon-revealer/pull/311#issuecomment-610470593

fix windows build

---

server/env.js
server/index.js
server/maps.js
server/notes.js
server/settings.js
server/util.js
src/dm-area/dm-map.js
src/dm-area/index.js
src/dm-area/modal.tsx
src/dm-area/note-editor/create-new-note-dialog-modal.tsx
src/dm-area/note-editor/delete-note-confirmation-dialog-modal.tsx
src/dm-area/overmind/note-store/note-store-actions.ts
src/dm-area/select-map-modal.js
src/dm-area/select-token-marker-reference-modal.tsx
src/hooks/use-svg-grid.js
src/http-request.ts
src/object-layer/dm-token-marker.js
src/player-area.js

Closes #202
Closes #353
Closes #355
Closes #354
Closes #356
Closes #357

race conditions, configurable data directory and other bug fixes

---

server/index.js
server/server.js

fix: close open client connections when shutting down

---

server/server.js

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/402

fix: create the data directory before trying to initialize the database

---

Dockerfile
package.json
server/tsconfig.json

move the tsconfig for the server to the server sub-directory for better code editor feedback
Visual Studio will give better type feedback that way

move the tsconfig for the server to the server sub-directory

---

src/dm-area/dm-map.js
src/feather-icons.tsx
src/hooks/use-async-clipboard-api.ts

👀
Requires chrome >= 76 AFAI. We might simply hide it for other browsers or use some kind of feature detection.
Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/414

feat: copy map image to the clipboard

---

src/dm-area/dm-map.js
src/dm-area/import-file-modal.tsx
src/dm-area/index.js
src/hooks/use-async-task.ts
src/hooks/use-drop-zone.ts

feat: import map/media library item via drag&drop

---

bin/dungeon-revealer

fix: use correct require path

---

.github/workflows/build-ci.yml
.github/workflows/build-docker.yml

actions: use DOCKER_REPO secret

---

.dockerignore
.github/workflows/build-binaries.yml
.github/workflows/build-docker.yml
Dockerfile
scripts/copy-node-bindings-path.js
scripts/print-node-bindings-path.js
scripts/set-git-tag-env.js

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/425

fix: binaries

---

README.md

This adds a few shields for our project. Inspired by [PlanarAlly](https://github.com/Kruptein/PlanarAlly).
I used [shields.io](https://shields.io/) to generate the images. There are tons of options. I'm open to any suggestions.

Add shields to Readme

---

src/dm-area/dm-map.js
src/object-layer/dm-token-marker.js
src/object-layer/token-marker.js

fix: invalid token drag position due to invalid ratio

---

src/player-area/player-area.js

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/450

fix: increase maximum canvas dimensions

---

Dockerfile

This will allow running `docker run -P` for automatically assigning a random free port to the container

feat: add expose hint for dockerfile

---

src/dm-area/dm-map.js
src/hooks/use-confirm-dialog.tsx

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/472

feat: confirm shroud reveal all

---

src/global-styles.tsx
src/note-search/note-search.tsx

closes https://github.com/dungeon-revealer/dungeon-revealer/issues/564

fix: search styles

---

docs/notes.md
server/graphql/modules/notes.ts
server/notes-db.ts
server/notes-lib.ts
src/chat/chat.tsx
src/dm-area/note-editor/note-editor.tsx
src/dm-area/token-info-aside/token-info-aside.tsx
src/draggable-window.tsx
src/feather-icons.tsx
src/horizontal-navigation.tsx
src/modal.tsx
src/note-search/note-search.tsx
type-definitions.graphql

feat: set note access from the note editor window.

---

README.md

docs: update docker links

---

server/chat.ts
server/graphql/modules/dice-roller-chat/dice-roller-chat.ts
server/graphql/modules/image.ts
server/server.js
src/cell-measure-context.tsx
src/chat/chat-message.tsx
src/chat/chat-messages.tsx
src/dm-area/components/sharable-image.tsx
src/dm-area/index.js
src/hooks/use-share-image-action.ts
src/player-area.tsx
type-definitions.graphql

Closes https://github.com/dungeon-revealer/dungeon-revealer/pull/605

feat: shared image is now shared to the chat

---

CONTRIBUTING.md
package.json

I did a clean install to double check that the build was enough and that everything worked after just running an install.

Updates the postinstall script to run build

---

CONTRIBUTING.md
package.json

This reverts commit cc753f397fd7da66829bdc6d28c22e8eb54f1700.

Revert "Updates the postinstall script to run build (#640)"

---

CONTRIBUTING.md

This just fixes the doc to have the commands in the correct order.

Updates instructions in contributing.md

---

server/note-import.ts

fix: stricter header regex

---

package-lock.json
package.json
server/graphql/index.ts
server/graphql/modules/dice-roller-chat/dice-roller-chat.ts
server/graphql/modules/notes.ts
server/graphql/modules/user/user.ts
server/notes-lib.ts
server/routes/graphql.ts
server/server.js
server/socket-session-store.ts
src/relay-environment.ts

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/659

✨ replace Socket.io GraphQL layer with abstraction packages

---

src/object-layer/token-marker-renderer.js

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/668

fix: remove token label maximum length of 5 characters.

---

.github/workflows/build-docker.yml
README.md
wiki/Install.md

Remove i386 docker builds

---

.github/workflows/build-binaries.yml
.github/workflows/build-docker.yml

[crazy-max/ghaction-docker-buildx](https://github.com/crazy-max/ghaction-docker-buildx) has been moved to [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action).

chore(deps): switch to docker/setup-buildx-action@v1

---

package-lock.json
package.json

on master the map will be stuck in drag state after dragging it around a bit

fix: broken drag behaviour caused by react-three-fiber issue

---

src/chat/chat-message.tsx
src/chat/chat-messages.tsx

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/809

fix: properly scroll chat to end

---

server/server.js
src/authenticated-app-shell.tsx
src/draggable-window.tsx

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/979

fix: hide non public notes without DM_PASSWORD being required

---

server/graphql/modules/notes.ts
server/graphql/modules/relay-spec/index.ts
server/index.js
server/notes-db.ts
server/notes-lib.ts
server/server.js
src/dm-area/note-editor/note-editor-side-bar.tsx
src/dm-area/token-info-aside/token-info-side-bar.tsx
type-definitions.graphql

feat: show all notes

---

server/graphql/modules/notes.ts
server/notes-lib.ts

This fixes the issue where the subscription for the notes list updates is not properly initialized because it fails to parse the provided cursor argument.

fix: handle empty parser represented by ""

---

src/chat/dice-roll-notes.tsx

This updates the dice roll notes to be more useful to complete beginners. 
Any input is welcome!

Update dice roll notes initial content

---

src/dm-area/dm-map.tsx
src/map-view.tsx
src/player-area.tsx

Closes https://github.com/dungeon-revealer/dungeon-revealer/pull/1301

fix: use the same text size when grid is hidden for players

---

src/leva-plugin/leva-plugin-note-preview.tsx
src/map-view.tsx
src/shared-token-menu.tsx

closes https://github.com/dungeon-revealer/dungeon-revealer/issues/1312

feat: open note attached to token above token properties

---

server/graphql/modules/map.ts
server/map-lib.ts
server/maps.ts
server/routes/map.js
src/dm-area/dm-area.tsx
src/map-context-menu-renderer.tsx
src/map-typings.tsx
src/map-view.tsx
type-definitions.graphql

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/1364

feat: implement rotating tokens

---

src/dm-area/token-image-cropper.tsx

closes https://github.com/dungeon-revealer/dungeon-revealer/issues/1363

feat: rotate image in image cropper

---

package-lock.json
package.json

fix: downgrade relay-hooks

---

src/map-view.tsx

fix: use degrees in token rotate

---

server/graphql/modules/notes.ts
server/notes-db.ts
server/notes-lib.ts

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/1591

fix: nullable decode

---

src/dm-area/token-image-cropper.tsx
src/dm-area/token-image-upload.tsx

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/1594

feat: use file name as default token image name

---

package-lock.json
package.json

Closes https://github.com/dungeon-revealer/dungeon-revealer/issues/1607

fix: broken map ping due broken dependency

---

scripts/prebuild.js

fix version reporting
Closes side note in #1609

fix: prebuild typo

---

README.md

Docs: heroku note

---

package-lock.json
package.json

Fix: npm install: doesn't work on Apple arm (M1, M2). (#1)

---

package-lock.json
package.json

This fixes deprecation warnings when installing deps

Update troika-three-text to latest version
